export interface Country {
  name: string;
  code: string;
  currency: string;
  currencyName: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", currency: "AFN", currencyName: "Afghan Afghani" },
  { name: "Argentina", code: "AR", currency: "ARS", currencyName: "Argentine Peso" },
  { name: "Australia", code: "AU", currency: "AUD", currencyName: "Australian Dollar" },
  { name: "Austria", code: "AT", currency: "EUR", currencyName: "Euro" },
  { name: "Bahrain", code: "BH", currency: "BHD", currencyName: "Bahraini Dinar" },
  { name: "Bangladesh", code: "BD", currency: "BDT", currencyName: "Bangladeshi Taka" },
  { name: "Belgium", code: "BE", currency: "EUR", currencyName: "Euro" },
  { name: "Brazil", code: "BR", currency: "BRL", currencyName: "Brazilian Real" },
  { name: "Cambodia", code: "KH", currency: "KHR", currencyName: "Cambodian Riel" },
  { name: "Canada", code: "CA", currency: "CAD", currencyName: "Canadian Dollar" },
  { name: "China", code: "CN", currency: "CNY", currencyName: "Chinese Yuan" },
  { name: "Colombia", code: "CO", currency: "COP", currencyName: "Colombian Peso" },
  { name: "Croatia", code: "HR", currency: "EUR", currencyName: "Euro" },
  { name: "Czech Republic", code: "CZ", currency: "CZK", currencyName: "Czech Koruna" },
  { name: "Denmark", code: "DK", currency: "DKK", currencyName: "Danish Krone" },
  { name: "Egypt", code: "EG", currency: "EGP", currencyName: "Egyptian Pound" },
  { name: "Finland", code: "FI", currency: "EUR", currencyName: "Euro" },
  { name: "France", code: "FR", currency: "EUR", currencyName: "Euro" },
  { name: "Germany", code: "DE", currency: "EUR", currencyName: "Euro" },
  { name: "Greece", code: "GR", currency: "EUR", currencyName: "Euro" },
  { name: "Hong Kong", code: "HK", currency: "HKD", currencyName: "Hong Kong Dollar" },
  { name: "Hungary", code: "HU", currency: "HUF", currencyName: "Hungarian Forint" },
  { name: "Iceland", code: "IS", currency: "ISK", currencyName: "Icelandic Króna" },
  { name: "India", code: "IN", currency: "INR", currencyName: "Indian Rupee" },
  { name: "Indonesia", code: "ID", currency: "IDR", currencyName: "Indonesian Rupiah" },
  { name: "Ireland", code: "IE", currency: "EUR", currencyName: "Euro" },
  { name: "Israel", code: "IL", currency: "ILS", currencyName: "Israeli Shekel" },
  { name: "Italy", code: "IT", currency: "EUR", currencyName: "Euro" },
  { name: "Japan", code: "JP", currency: "JPY", currencyName: "Japanese Yen" },
  { name: "Jordan", code: "JO", currency: "JOD", currencyName: "Jordanian Dinar" },
  { name: "Kenya", code: "KE", currency: "KES", currencyName: "Kenyan Shilling" },
  { name: "Laos", code: "LA", currency: "LAK", currencyName: "Lao Kip" },
  { name: "Malaysia", code: "MY", currency: "MYR", currencyName: "Malaysian Ringgit" },
  { name: "Maldives", code: "MV", currency: "MVR", currencyName: "Maldivian Rufiyaa" },
  { name: "Mexico", code: "MX", currency: "MXN", currencyName: "Mexican Peso" },
  { name: "Morocco", code: "MA", currency: "MAD", currencyName: "Moroccan Dirham" },
  { name: "Myanmar", code: "MM", currency: "MMK", currencyName: "Myanmar Kyat" },
  { name: "Nepal", code: "NP", currency: "NPR", currencyName: "Nepalese Rupee" },
  { name: "Netherlands", code: "NL", currency: "EUR", currencyName: "Euro" },
  { name: "New Zealand", code: "NZ", currency: "NZD", currencyName: "New Zealand Dollar" },
  { name: "Norway", code: "NO", currency: "NOK", currencyName: "Norwegian Krone" },
  { name: "Oman", code: "OM", currency: "OMR", currencyName: "Omani Rial" },
  { name: "Pakistan", code: "PK", currency: "PKR", currencyName: "Pakistani Rupee" },
  { name: "Peru", code: "PE", currency: "PEN", currencyName: "Peruvian Sol" },
  { name: "Philippines", code: "PH", currency: "PHP", currencyName: "Philippine Peso" },
  { name: "Poland", code: "PL", currency: "PLN", currencyName: "Polish Złoty" },
  { name: "Portugal", code: "PT", currency: "EUR", currencyName: "Euro" },
  { name: "Qatar", code: "QA", currency: "QAR", currencyName: "Qatari Riyal" },
  { name: "Romania", code: "RO", currency: "RON", currencyName: "Romanian Leu" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", currencyName: "Saudi Riyal" },
  { name: "Singapore", code: "SG", currency: "SGD", currencyName: "Singapore Dollar" },
  { name: "South Africa", code: "ZA", currency: "ZAR", currencyName: "South African Rand" },
  { name: "South Korea", code: "KR", currency: "KRW", currencyName: "South Korean Won" },
  { name: "Spain", code: "ES", currency: "EUR", currencyName: "Euro" },
  { name: "Sri Lanka", code: "LK", currency: "LKR", currencyName: "Sri Lankan Rupee" },
  { name: "Sweden", code: "SE", currency: "SEK", currencyName: "Swedish Krona" },
  { name: "Switzerland", code: "CH", currency: "CHF", currencyName: "Swiss Franc" },
  { name: "Taiwan", code: "TW", currency: "TWD", currencyName: "New Taiwan Dollar" },
  { name: "Tanzania", code: "TZ", currency: "TZS", currencyName: "Tanzanian Shilling" },
  { name: "Thailand", code: "TH", currency: "THB", currencyName: "Thai Baht" },
  { name: "Turkey", code: "TR", currency: "TRY", currencyName: "Turkish Lira" },
  { name: "UAE", code: "AE", currency: "AED", currencyName: "UAE Dirham" },
  { name: "Uganda", code: "UG", currency: "UGX", currencyName: "Ugandan Shilling" },
  { name: "Ukraine", code: "UA", currency: "UAH", currencyName: "Ukrainian Hryvnia" },
  { name: "United Kingdom", code: "GB", currency: "GBP", currencyName: "British Pound" },
  { name: "United States", code: "US", currency: "USD", currencyName: "US Dollar" },
  { name: "Vietnam", code: "VN", currency: "VND", currencyName: "Vietnamese Dong" },
];

// Approximate rates: 1 INR = X units of currency
export const RATES_PER_INR: Record<string, number> = {
  INR: 1,
  USD: 0.012,
  EUR: 0.011,
  GBP: 0.0095,
  JPY: 1.8,
  AUD: 0.018,
  CAD: 0.016,
  CHF: 0.011,
  SGD: 0.016,
  HKD: 0.094,
  MYR: 0.056,
  THB: 0.43,
  IDR: 191,
  VND: 297,
  PHP: 0.68,
  KRW: 16.2,
  CNY: 0.086,
  AED: 0.044,
  SAR: 0.045,
  QAR: 0.044,
  BHD: 0.0045,
  OMR: 0.0046,
  JOD: 0.0085,
  NZD: 0.020,
  ZAR: 0.22,
  MXN: 0.20,
  BRL: 0.060,
  ARS: 11.0,
  TRY: 0.39,
  PLN: 0.049,
  CZK: 0.28,
  HUF: 4.3,
  NOK: 0.13,
  SEK: 0.13,
  DKK: 0.083,
  TWD: 0.38,
  LKR: 3.6,
  NPR: 1.6,
  PKR: 3.3,
  BDT: 1.33,
  EGP: 0.59,
  KES: 1.56,
  TZS: 31.5,
  UGX: 45,
  MAD: 0.12,
  MVR: 0.185,
  KHR: 49,
  LAK: 258,
  MMK: 25,
  ILS: 0.045,
  AFN: 0.85,
  COP: 49.5,
  PEN: 0.046,
  IDR: 191,
  RON: 0.055,
  UAH: 0.50,
  ISK: 1.65,
  GBP: 0.0095,
};

export function convertFromINR(amountINR: number, toCurrency: string): number {
  const rate = RATES_PER_INR[toCurrency] ?? 1;
  return amountINR * rate;
}

export function formatCurrency(amount: number, currency: string): string {
  const symbols: Record<string, string> = {
    INR: '₹', USD: '$', EUR: '€', GBP: '£', JPY: '¥', CNY: '¥',
    AUD: 'A$', CAD: 'C$', SGD: 'S$', HKD: 'HK$', MYR: 'RM',
    THB: '฿', IDR: 'Rp', VND: '₫', PHP: '₱', KRW: '₩',
    AED: 'AED', SAR: 'SAR', QAR: 'QAR', CHF: 'CHF',
    TRY: '₺', BRL: 'R$', ZAR: 'R', NZD: 'NZ$',
  };
  const sym = symbols[currency] || currency + ' ';
  if (Math.abs(amount) >= 1000) {
    return sym + amount.toLocaleString('en-IN', { maximumFractionDigits: 0 });
  }
  return sym + amount.toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}
